name: Verify

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ASDF
        uses: asdf-vm/actions/install@v3
      - name: Build
        run: |
          task build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ASDF
        uses: asdf-vm/actions/install@v3
      - name: Test
        run: |
          task test
